### PR TITLE
Load local samples files (.cs/.vb)

### PR DESCRIPTION
**Pull request by Enigmatic331**
As titled - Added a simple functionality to allow local files to be loaded into the editor. Mostly to make it slightly easier to share snippets (in files) instead of having to pass around and copy paste entire code blocks.

To round up this functionality, during the coming days will include also a "Save As" functionality so Playground users could edit samples to their liking and save it to a local copy. Also, the "Load from Gist/Github" functionality we've talked about. :)

### CODE REVIEW

**Comment by juanfranblanco** [comment]
" Also, the "Load from Gist/Github" functionality we've talked about. :)", no that is very limiting "Load from Url"..

**Comment by Enigmatic331** [comment]
Ah sorry - I should rephrase - Grab code from URL (not necessarily Gist/Github, as long as it's a URL which returns plaintext codes of some form).

**Comment by juanfranblanco** [comment]
Don't worry :) Also what I meant for LocalStorage, it is to use something like https://github.com/BlazorExtensions/Storage

**Comment by juanfranblanco** [comment]
Oh I forgot to say.. this is great thanks!! (but you know I said already.. just not here :D)

**Pull request merged**
