### PR TITLE
Feat sample convert unit

### PR DESCRIPTION
**Pull request by anegg0**
Added other samples:
- converting unit
- connecting to INFURA
- managing chain ID

### CODE REVIEW

**Comment by anegg0** [comment]
for your review @juanfranblanco

**Comment by juanfranblanco** [comment]
@anegg0 Managed accounts are not going to be possible if not pointing to a localhost, maybe separate that into another sample?

**Comment by anegg0** [comment]
> @anegg0 Managed accounts are not going to be possible if not pointing to a localhost, maybe separate that into another sample?

I was hoping to use the Azure instance to do that, but I can't connect to it for now.

**Comment by anegg0** [comment]
@juanfranblanco the code is now fixed. All samples use either INFURA or the Azure instance. All except the one explaining Chain ID, as it's meant to help users learn how to change their genesis file, which can only be done on a chain they control.

**Comment by juanfranblanco** [comment]
@anegg0 the address is http://testchain.nethereum.com:8545 don't use the IP as it may change :)

**Pull request merged**
