### PR TITLE
Update 1001.txt

### PR DESCRIPTION
**Pull request by moodmosaic**
Remove unused reference.

### CODE REVIEW

**Comment by juanfranblanco** [comment]
Thanks, but I want to keep those references, to allow users autocomplete when experimenting.

**Comment by moodmosaic** [comment]
Oh, I see. Perhaps we can at least sort/order them? e.g.

```diff
  using System;
  using System.Text;
- using Nethereum.Hex.HexConvertors.Extensions;
  using System.Threading.Tasks;
+ using Nethereum.Hex.HexConvertors.Extensions;
  using Nethereum.Web3;
```

**Comment by juanfranblanco** [comment]
Yes, good idea, all will need to be migrated to Nethereum 4.x so it will be a good time to sort that out for all examples. BTW I love hedgehog, when I add the capability to add Validators to all the contract interactions it will be great to add examples to add tests with Hedgehog.

**Comment by moodmosaic** [comment]
I'd be happy to help ❤️ We also [support LINQ via Hedgehog.Linq namespace](https://github.com/hedgehogqa/fsharp-hedgehog/releases/tag/v0.10.0) ([example](https://twitter.com/nikosbaxevanis/status/1359530069820137475)).

**Comment by juanfranblanco** [comment]
Yes I saw that, it is great. I will surely will need your help to create a good example. My thought for years was to put a generic validator "interceptor" based on Types, and specific contract, (when sending / signing / estimating a transaction, making a query, etc) so simply ending up with a registry of validators. This is another reason for separating Commands and Queries per FunctionMessages, DeploymentMessages, etc. So here it can fit very well, there were also other people on the community thinking of using f# to create some generic kind of Plex tester, so my guess is that they thought of hedgehog too.

**Pull request closed without merging**
